# Automatically publish documentation to GitHub Pages

name: Code Checks

on:
  workflow_dispatch:
  # TODO: We will run this on every push to main

jobs:
  publish-website:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install uv and enable caching
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"
        version: "0.5.4"

    - name: Set up Python with uv
      run: uv python install

    - name: Build documentation
      run: |
        sphinx-build -M html sphinx/source/ sphinx/build/ --fail-on-warning --fresh-env --write-all

    - name: Upload documentation files as artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: sphinx/build/html

    - name: Clean up uv cache
      run: uv cache prune --ci
