# Automatically build and publish the package to PyPI

name: Publish PnPQ to PyPI

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  check-codes:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install uv and enable caching
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"
        version: "0.5.26"

    - name: Set up Python with uv
      run: uv python install

    - name: Build package
      run: uv build

    - name: Publish package to PyPI
      run: uv publish --index testpypi
